Furniture = {
    {
        name = 'Chairs',
        title = 'Chairs', -- Menu title
        desc = "View assorted chairs",
        { propModel = "p_chair20x",        displayName = "Red Patterned Chair",  costToBuy = 20, sellFor = 18 },
        { propModel = "p_chair38x",        displayName = "Yellow Elegant Chair", costToBuy = 20, sellFor = 18 },
        { propModel = "p_chairdining01x",  displayName = "White Elegant Chair",  costToBuy = 20, sellFor = 18 },
        { propModel = "p_chair06x",        displayName = "Varnished Chair",      costToBuy = 15, sellFor = 13 },
        { propModel = "p_diningchairs01x", displayName = "Chair with Armrests",  costToBuy = 15, sellFor = 13 },
        { propModel = "p_windsorchair03x", displayName = "Brown Chair",          costToBuy = 15, sellFor = 13 },
        { propModel = "p_chair02x",        displayName = "Old Blue Chair",       costToBuy = 15, sellFor = 13 },
        { propModel = "s_bfchair04x",      displayName = "Wooden Chair",         costToBuy = 15, sellFor = 13 },
        { propModel = "p_chair_cs05x",     displayName = "Polished Chair",       costToBuy = 15, sellFor = 13 },
        { propModel = "p_chairfolding02x", displayName = "Folding Chair",        costToBuy = 5,  sellFor = 4 },
        { propModel = "p_chair_crate02x",  displayName = "Wooden Crate",         costToBuy = 3,  sellFor = 2 },
        { propModel = "p_chairdesk02x",    displayName = "Red Leather Armchair", costToBuy = 40, sellFor = 38 },
        { propModel = "p_chairwicker02x",  displayName = "Wicker Armchair",      costToBuy = 25, sellFor = 23 },
        { propModel = "p_chairrocking02x", displayName = "Rocking Chair",        costToBuy = 18, sellFor = 16 },
        { propModel = "p_stool07x",        displayName = "Varnished Stool",      costToBuy = 15, sellFor = 13 },
        { propModel = "p_stool01x",        displayName = "Wooden Stool",         costToBuy = 12, sellFor = 11 },
        { propModel = "p_stool03x",        displayName = "Worn Stool",           costToBuy = 5,  sellFor = 4 },
    },
    {
        name = 'Benches',
        title = 'Benches',
        desc = "View assorted benches",
        { propModel = "p_bench03x",          displayName = "Homemade Bench",  costToBuy = 10, sellFor = 8 },
        { propModel = "p_bench09x",          displayName = "Wooden Bench",    costToBuy = 15, sellFor = 13 },
        { propModel = "p_bench08bx",         displayName = "Red Bench",       costToBuy = 15, sellFor = 13 },
        { propModel = "p_benchannsaloon01x", displayName = "Dark Wood Bench", costToBuy = 25, sellFor = 23 },
        { propModel = "p_benchch01x",        displayName = "Wooden Pew",      costToBuy = 25, sellFor = 23 },
        { propModel = "p_bench15x",          displayName = "City Bench",      costToBuy = 35, sellFor = 33 },
    },
    {
        name = 'Tables',
        title = 'Tables',
        desc = "View assorted tables",
        { propModel = "p_table04x",   displayName = "Kitchen Table",                 costToBuy = 15, sellFor = 13 },
        { propModel = "p_table55x",   displayName = "Painted Table",                 costToBuy = 30, sellFor = 28 },
        { propModel = "p_table51x",   displayName = "Table with White Tablecloth",   costToBuy = 30, sellFor = 28 },
        { propModel = "p_table14x",   displayName = "Table with Colored Tablecloth", costToBuy = 25, sellFor = 13 },
        { propModel = "p_table48x",   displayName = "Wooden Table",                  costToBuy = 20, sellFor = 18 },
        { propModel = "p_table47x",   displayName = "Small Wooden Table",            costToBuy = 15, sellFor = 13 },
        { propModel = "p_table46x",   displayName = "Old Wooden Table",              costToBuy = 15, sellFor = 13 },
        { propModel = "p_table42_cs", displayName = "Old Wooden Side Table",         costToBuy = 10, sellFor = 8 },
        { propModel = "p_tablehob1x", displayName = "Broken Table",                  costToBuy = 5,  sellFor = 4 },
        { propModel = "p_desk14x",    displayName = "Varnished Desk",                costToBuy = 50, sellFor = 45 },
        { propModel = "p_desk04x",    displayName = "Desk",                          costToBuy = 45, sellFor = 43 },
        { propModel = "p_desk01x",    displayName = "Work Desk",                     costToBuy = 25, sellFor = 23 },
        { propModel = "s_desk01x",    displayName = "Old Work Desk",                 costToBuy = 15, sellFor = 13 },
    },
    {
        name = 'Beds',
        title = 'Beds',
        desc = "View assorted beds",
        { propModel = "p_bedrollopen03x",     displayName = "White Sleeping Bag",     costToBuy = 10, sellFor = 8 },
        { propModel = "s_bedrollfurlined01x", displayName = "Red Sleeping Bag",       costToBuy = 10, sellFor = 8 },
        { propModel = "p_bedindian01x",       displayName = "Homemade Bed",           costToBuy = 10, sellFor = 8 },
        { propModel = "p_bed03x",             displayName = "Old Bed",                costToBuy = 15, sellFor = 13 },
        { propModel = "p_bed14x",             displayName = "Dirty Bed",              costToBuy = 15, sellFor = 13 },
        { propModel = "p_bed21x",             displayName = "Bed with Blue Blanket",  costToBuy = 30, sellFor = 28 },
        { propModel = "p_bed17x",             displayName = "Bed with Brown Blanket", costToBuy = 30, sellFor = 28 },
        { propModel = "p_bed05x",             displayName = "Bed with Lace Blanket",  costToBuy = 40, sellFor = 38 },
        { propModel = "p_bed22x",             displayName = "High Bed",               costToBuy = 50, sellFor = 48 },
        { propModel = "p_bed20madex",         displayName = "Double Bed",             costToBuy = 80, sellFor = 78 },
    },
    {
        name = 'Storage',
        title = 'Storage',
        desc = "View assorted cabinets",
        { propModel = "p_cupboard01x",     displayName = "Old Wall Cabinet",   costToBuy = 5,  sellFor = 4 },
        { propModel = "p_cupboard06x",     displayName = "Old Blue Cabinet",   costToBuy = 10, sellFor = 8 },
        { propModel = "p_cupboard03x",     displayName = "Old White Cabinet",  costToBuy = 10, sellFor = 8 },
        { propModel = "p_bookcase01x",     displayName = "Large Buffet",       costToBuy = 25, sellFor = 23 },
        { propModel = "p_cupboard02x",     displayName = "Small Buffet",       costToBuy = 20, sellFor = 18 },
        { propModel = "p_shelfwall02x",    displayName = "Wooden Shelf",       costToBuy = 5,  sellFor = 4 },
        { propModel = "p_kitchenhutch01x", displayName = "Kitchen Buffet",     costToBuy = 30, sellFor = 28 },
        { propModel = "p_shelf06x",        displayName = "Dark Wood Buffet",   costToBuy = 40, sellFor = 38 },
        { propModel = "p_dresser11x",      displayName = "Dark Dresser",       costToBuy = 35, sellFor = 33 },
        { propModel = "p_shelfwall05x",    displayName = "Varnished Shelf",    costToBuy = 10, sellFor = 9 },
        { propModel = "p_armoir08x",       displayName = "Small Wardrobe",     costToBuy = 30, sellFor = 28 },
        { propModel = "p_armoir04x",       displayName = "Large Wardrobe",     costToBuy = 40, sellFor = 38 },
        { propModel = "p_armoir07x",       displayName = "Varnished Wardrobe", costToBuy = 50, sellFor = 48 },
    },
    {
        name = 'Decor',
        title = 'Decor',
        desc = "View miscellaneous items",
        { propModel = "p_candlegroup05x",      displayName = "Candle",              costToBuy = 1,  sellFor = 0 },
        { propModel = "p_candlestand",         displayName = "Candlestick",         costToBuy = 3,  sellFor = 2 },
        { propModel = "s_interact_lantern01x", displayName = "Lantern",             costToBuy = 10, sellFor = 9 },
        { propModel = "p_lanternstick09x",     displayName = "Lantern on a Stick",  costToBuy = 10, sellFor = 9 },
        { propModel = "p_lamp25x",             displayName = "Gas Lamp with Shade", costToBuy = 10, sellFor = 9 },
        { propModel = "p_oillamp01x",          displayName = "Gas Lamp",            costToBuy = 8,  sellFor = 7 },
        { propModel = "p_dressmirror01x",      displayName = "Large Mirror",        costToBuy = 35, sellFor = 33 },
        { propModel = "p_mirror03x",           displayName = "Regular Mirror",      costToBuy = 20, sellFor = 18 },
        { propModel = "p_mirror_shave01x",     displayName = "Shaving Mirror",      costToBuy = 10, sellFor = 9 },
        { propModel = "p_hatstand01xng",       displayName = "Floor Coat Stand",    costToBuy = 15, sellFor = 13 },
        { propModel = "p_coatrack04x",         displayName = "Wall Coat Rack",      costToBuy = 10, sellFor = 9 },
        { propModel = "p_alarmclock01x",       displayName = "Alarm Clock",         costToBuy = 35, sellFor = 33 },
        { propModel = "val_bank_clock",        displayName = "Wall Clock",          costToBuy = 40, sellFor = 38 },
        { propModel = "p_wallclocklrg01x",     displayName = "Large Clock",         costToBuy = 50, sellFor = 48 },
        { propModel = "p_pot_flowerarng01x",   displayName = "Bouquet in a Pot",    costToBuy = 15, sellFor = 13 },
        { propModel = "p_pot_flowerarng05x",   displayName = "Flowers in a Vase",   costToBuy = 15, sellFor = 13 },
        { propModel = "p_pot_flowerarng07x",   displayName = "Plant in a Pot",      costToBuy = 15, sellFor = 13 },
        { propModel = "p_pot_flowerarng11x",   displayName = "Flowers in a Glass",  costToBuy = 3,  sellFor = 2 },
        { propModel = "p_gunsmithprops20x",    displayName = "Deer Antlers",        costToBuy = 20, sellFor = 18 },
        { propModel = "p_gunsmithprops17x",    displayName = "Large Deer Antlers",  costToBuy = 30, sellFor = 28 },
    },
    {
        name = 'Kitchen',
        title = 'Kitchen',
        desc = "View assorted kitchen items",
        { propModel = "p_sink02x",         displayName = "Large Sink with Faucet", costToBuy = 90,  sellFor = 88 },
        { propModel = "p_stove04x",        displayName = "Bourgeois Stove",        costToBuy = 100, sellFor = 98 },
        { propModel = "p_stove06x",        displayName = "Old Stove",              costToBuy = 120, sellFor = 118 },
        { propModel = "p_stove01x",        displayName = "Large Stove",            costToBuy = 150, sellFor = 148 },
        { propModel = "p_cookingtools01x", displayName = "Wall Kitchenware",       costToBuy = 10,  sellFor = 9 },
    },
    {
        name = 'Bathroom',
        title = 'Bathroom',
        desc = "View assorted bathroom items",
        { propModel = "p_washtub02x",            displayName = "Bathing Tub",           costToBuy = 10,  sellFor = 9 },
        { propModel = "p_washbasin01x",          displayName = "Old Washbasin",         costToBuy = 15,  sellFor = 13 },
        { propModel = "p_washbasndoctor01x",     displayName = "Washbasin with Mirror", costToBuy = 25,  sellFor = 23 },
        { propModel = "p_sink03x",               displayName = "Ceramic Washbasin",     costToBuy = 35,  sellFor = 33 },
        { propModel = "p_bath02x",               displayName = "Bronze Bathtub",        costToBuy = 250, sellFor = 248 },
        { propModel = "p_val_hotel_int_tub_01x", displayName = "Wood-Clad Bathtub",     costToBuy = 100, sellFor = 98 },
        { propModel = "p_toiletchair01x",        displayName = "Night Toilet",          costToBuy = 15,  sellFor = 13 },
    },
    {
        name = 'Yard',
        title = 'Yard',
        desc = "View assorted yard items",
        { propModel = "p_waterpump01x",      displayName = "Iron Hydrant",        costToBuy = 80, sellFor = 78 },
        { propModel = "p_wellpumpnbx01x",    displayName = "Old Hydrant",         costToBuy = 60, sellFor = 58 },
        { propModel = "p_hng_toi",           displayName = "Outdoor Toilet",      costToBuy = 30, sellFor = 28 },
        { propModel = "p_hitchingpost01x",   displayName = "Large Hitching Post", costToBuy = 10, sellFor = 9 },
        { propModel = "p_hitchingpost04x",   displayName = "Small Hitching Post", costToBuy = 5,  sellFor = 4 },
        { propModel = "p_toolbox01x",        displayName = "Toolbox",             costToBuy = 10, sellFor = 9 },
        { propModel = "p_group_barrelcor01", displayName = "Barrel with Tools",   costToBuy = 10, sellFor = 9 },
    },
}